// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: amberdb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_amberdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_amberdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_amberdb_proto_rawDescGZIP(), []int{0}
}

type TxnID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnID) Reset() {
	*x = TxnID{}
	mi := &file_amberdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnID) ProtoMessage() {}

func (x *TxnID) ProtoReflect() protoreflect.Message {
	mi := &file_amberdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnID.ProtoReflect.Descriptor instead.
func (*TxnID) Descriptor() ([]byte, []int) {
	return file_amberdb_proto_rawDescGZIP(), []int{1}
}

func (x *TxnID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TxId          string                 `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_amberdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amberdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_amberdb_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WriteRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ReadTimestamp string                 `protobuf:"bytes,2,opt,name=read_timestamp,json=readTimestamp,proto3" json:"read_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_amberdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amberdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_amberdb_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadRequest) GetReadTimestamp() string {
	if x != nil {
		return x.ReadTimestamp
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_amberdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amberdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_amberdb_proto_rawDescGZIP(), []int{4}
}

func (x *ReadResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_amberdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_amberdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_amberdb_proto_rawDescGZIP(), []int{5}
}

func (x *Status) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_amberdb_proto protoreflect.FileDescriptor

const file_amberdb_proto_rawDesc = "" +
	"\n" +
	"\ramberdb.proto\x12\aamberdb\"\a\n" +
	"\x05Empty\"\x17\n" +
	"\x05TxnID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\fWriteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x13\n" +
	"\x05tx_id\x18\x03 \x01(\tR\x04txId\"F\n" +
	"\vReadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x0eread_timestamp\x18\x02 \x01(\tR\rreadTimestamp\"$\n" +
	"\fReadResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"<\n" +
	"\x06Status\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfd\x01\n" +
	"\fAmberService\x122\n" +
	"\x10BeginTransaction\x12\x0e.amberdb.Empty\x1a\x0e.amberdb.TxnID\x12/\n" +
	"\x05Write\x12\x15.amberdb.WriteRequest\x1a\x0f.amberdb.Status\x123\n" +
	"\x04Read\x12\x14.amberdb.ReadRequest\x1a\x15.amberdb.ReadResponse\x12)\n" +
	"\x06Commit\x12\x0e.amberdb.TxnID\x1a\x0f.amberdb.Status\x12(\n" +
	"\x05Abort\x12\x0e.amberdb.TxnID\x1a\x0f.amberdb.StatusB\tZ\a./protob\x06proto3"

var (
	file_amberdb_proto_rawDescOnce sync.Once
	file_amberdb_proto_rawDescData []byte
)

func file_amberdb_proto_rawDescGZIP() []byte {
	file_amberdb_proto_rawDescOnce.Do(func() {
		file_amberdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amberdb_proto_rawDesc), len(file_amberdb_proto_rawDesc)))
	})
	return file_amberdb_proto_rawDescData
}

var file_amberdb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_amberdb_proto_goTypes = []any{
	(*Empty)(nil),        // 0: amberdb.Empty
	(*TxnID)(nil),        // 1: amberdb.TxnID
	(*WriteRequest)(nil), // 2: amberdb.WriteRequest
	(*ReadRequest)(nil),  // 3: amberdb.ReadRequest
	(*ReadResponse)(nil), // 4: amberdb.ReadResponse
	(*Status)(nil),       // 5: amberdb.Status
}
var file_amberdb_proto_depIdxs = []int32{
	0, // 0: amberdb.AmberService.BeginTransaction:input_type -> amberdb.Empty
	2, // 1: amberdb.AmberService.Write:input_type -> amberdb.WriteRequest
	3, // 2: amberdb.AmberService.Read:input_type -> amberdb.ReadRequest
	1, // 3: amberdb.AmberService.Commit:input_type -> amberdb.TxnID
	1, // 4: amberdb.AmberService.Abort:input_type -> amberdb.TxnID
	1, // 5: amberdb.AmberService.BeginTransaction:output_type -> amberdb.TxnID
	5, // 6: amberdb.AmberService.Write:output_type -> amberdb.Status
	4, // 7: amberdb.AmberService.Read:output_type -> amberdb.ReadResponse
	5, // 8: amberdb.AmberService.Commit:output_type -> amberdb.Status
	5, // 9: amberdb.AmberService.Abort:output_type -> amberdb.Status
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_amberdb_proto_init() }
func file_amberdb_proto_init() {
	if File_amberdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amberdb_proto_rawDesc), len(file_amberdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_amberdb_proto_goTypes,
		DependencyIndexes: file_amberdb_proto_depIdxs,
		MessageInfos:      file_amberdb_proto_msgTypes,
	}.Build()
	File_amberdb_proto = out.File
	file_amberdb_proto_goTypes = nil
	file_amberdb_proto_depIdxs = nil
}
